version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: NL7PiF67HiZAN8i
      MYSQL_DATABASE: biblioteca_db
      MYSQL_USER: user_biblioteca
      MYSQL_PASSWORD: NL7PiF67HiZAN8i
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/db/setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro 

  app:
    build: .
    restart: always
    ports:
      - "8088:3000"
    environment:
      DB_HOST: db
      DB_USER: user_biblioteca
      DB_PASSWORD: NL7PiF67HiZAN8i
      DB_NAME: biblioteca_db
      DB_PORT: 3306
    depends_on:
      - db
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app/src 

volumes:
  db_data: